# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91a3cdaeefeea3d4a5a681c5d073fe4521cbe19d988c820bc5cbf98780ae456521c8916d29e85ebfa66b37bd7f41519a43b36e7dd7810b2a9671e8fa73fef4d7

test:
  secret_key_base: 1f6a5a3093436c9826f137554a734421f8be44aaf7e76b5d7ce3c43c92fa93423b972499cdd9df7d7054d41bf38cb3605855388455806cb63c91d7451325b782

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
